services:
  url-shortener:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: url-shortener-service
    ports:
      - "8087:8087"
    depends_on:
      - redis
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SPRING_DATASOURCE_URL=jdbc:postgresql://url-postgres:5432/url_shortener
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - indeece-net
  redis:
    image: redis:latest
    container_name: proselyte-redis
    ports:
      - "6379:6379"
    networks:
      - indeece-net

  postgres:
    image: postgres:15-alpine
    container_name: url-postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - indeece-net

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    networks:
      - indeece-net

volumes:
  redis-insight:
  pgdata:

networks:
  indeece-net:
    driver: bridge